#site settings
title: "Collective Realms"
subtitle: "Fantasy and Science Fiction Magazine"
description: "Fantasy and Science Fiction Magazine"
baseurl: "/"
url: "http://collectiverealms.com/"
email: "collectiverealms@gmail.com"
avatar: "https://avatars1.githubusercontent.com/u/40450187?s=460&v=4"
cover: "assets/header_image.png"
logo: "assets/logo.png"

#build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap

    
 # Google analytics
# ga_tracking_id: "UA-121187519-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: fiction
    desc: "Short stories."

  - cat: art
    desc: "Artwork"

social:
  - name: GitHub
    icon: github
    username: collectiverealms
    url: https://github.com/collectiverealms
    desc: Fork me on GitHub
    share: false

  
  - name: Tumblr
    icon: tumblr
    username: collectiverealms
    url: https://collectiverealms.tumblr.com
    desc: Follow me on Tumblr
    share: false
    
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"


